# Generated by Django 5.2.6 on 2025-10-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='y_value',
        ),
        migrations.AlterField(
            model_name='calculation',
            name='is_arbitrage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='x_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
